language: go
go:
- 1.11
script:
- make build
- make test
before_deploy: make release-build
deploy:
  provider: releases
  api_key:
    secure: U/JM7jdSxbqYan39dirrWAuApRm3J/DmT3syIERQfWJNLfDpTDhCzK70wUbemcPrmz7eudIab8wcbRJs9dkO4iG87hrhejhbfH/K8Ajl4YV5+fhewPB5ZRpKIOHxlRUdM6lKqjcBAKNCQBetKAfGVJFafBnI7tKJQg0mrDfBWcJq1zvTzl8T/6S7OPqKDJWgvbmmcrHeWrXtGe07FD0qMFaMe5fhB3/orU4nfTbI5hoKjwH++o3D0sRfipzxqsnKJBi36MiEg95rBA+cjbKsVo6aneI9pIcfxWb95lRhS0oL7fQB4MEvoT3R+gPdrVATwFXQhl9M1D6bq7hWguwqgcSovL9+eibbvj21HIER9Wg6M343ewgdy346QqIuUn1wPLohgw8oCIqaw0jVncYJnlNonT3B4NR+IZdcTBR57F8sv3EbIc54KttBHh5E8SZJs6NsZSj13yILsQ2JXsjDq3u0DPpEuYkazRauyn6EUNNvTA+dkAvfS8+c1wgxkgKDSLiGR9FXp2iN3a1kETqJ1IbbOVZcX8YXhIJB95PgoQf5qjk1kju4tCZWkC/NFlXjk17jXAMlMT2PUk9LrXq+tp5FT9RMez7NKEKoVrsYzay+XRgRG3dHDk35Ipsw2N+BCOwARin9atEu96BTg1p2bFy2sifMD2kkJhqpBLUMfjI=
  file:
  - build/nsq_exporter_darwin_amd64
  - build/nsq_exporter_freebsd_386
  - build/nsq_exporter_freebsd_amd64
  - build/nsq_exporter_linux_386
  - build/nsq_exporter_linux_amd64
  - build/nsq_exporter_linux_arm
  - build/nsq_exporter_linux_arm64
  - build/nsq_exporter_windows_386.exe
  - build/nsq_exporter_windows_amd64.exe
  on:
    repo: pedro3692/nsq_exporter
    tags: true
